# Publish Main to https://maven.minecrafttas.com/main
name: Publish Main

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'MinecraftTAS/BigArrayList'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.13
    - name: Publish
      run: gradle publishAllPublicationsToMinecrafttasMainRepository -Prelease=true -PminecrafttasMainUsername=${{ secrets.MAVEN_NAME }} -PminecrafttasMainPassword=${{ secrets.MAVEN_SECRET }}
