name: test

on:
  pull_request:
    branches:
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.13
    - name: Build
      run: gradle build
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: TestResult
        path: build/test-results/test/*.xml
        retention-days: 1
